### ISSUE TITLE
Move user.css to individual template

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#1007]
Potential gotchas I haven't thought about ?

**Comment by ecartz** [comment]
I think that individual templates should provide their own copies of the user.css file.  That doesn't necessarily require moving the current one.  I would rather change things so that it automatically looks for templates/whatever_name/images/user.css and includes it if it exists, by either simply blatting it out or linking to it.  Then we could stop loading it from the current location.  

This is one of the things that I had in mind as part of the code drop @ 100.  The idea being that we'd provide default files that users could copy into their templates/custom directory tree and customize.  So we'd be providing no files that a user would need to edit, keeping a good separation between core and user modifications.

**Comment by gburton** [comment]
What I'd like to do is keep it simple;

1. move the user.css to /templates/default/
2. update the hook (in templates/default) to point at /templates/default/user.css

This will, I believe, result in fewer people asking questions.  Thoughts?
Bear in mind that template makers are generally clueless about functionality.

I have tested this, all works well.  I have the push ready to go.  I have not just pushed it as the template functionality is your area of exertise.

**Comment by azpro-git** [comment]
`move the user.css to /templates/default/`

`update the hook (in templates/default) to point at /templates/default/user.css`

Agree - Do no put it in /images/ .... that seems very odd IMHO

**Comment by ecartz** [comment]
I'll rename images to make it more sensible.  

I do not want anything in the bottom directory except more directories.
