### ISSUE TITLE
add loading lazy tag to tep_image function

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1008]
I saw that the loading="lazy" tag has been added to the product info gallery modules.
Wouldn't it make sense to add it to the tep_image function so it would be used for all images. I believe it would be most useful for the product listings. Or am I wrong?

**Comment by ecartz** [comment]
Wouldn't we actually want to do the reverse on the product listing?  I.e. instead of lazy loading, for most images on the screen, we would want them to prefetch instead.  So they load as soon as possible.  

It would only make sense to lazy load images on the product listing if they are "below the fold" meaning not shown on the viewable screen.  For most Phoenix installs, I suspect that people size the product listings such that all the products show on the screen in the normal desktop view.  Perhaps some Javascript for alternate sizes would make sense.  Because again, the images below the fold could be lazy loaded.  Overall, I think that this is more complicated than would make sense for core at this time.  It's probably easier just to plan the product listings to show in the viewport and not require scrolling.  Perhaps someone with, say, an image thumbnailer App might want to look into more complicated options and see how well they work.  

The gallery is different.  Those images don't show until the user selects them.  So if they aren't loaded until after the rest of the page, it doesn't hurt anything.  I.e. they are all off-line images.

**Comment by raiwa** [comment]
I was mainly considering this important for mobile where we have a one column product listing. Maybe it would be possible to script it to be used for mobile viewport only. Otherwise I may think of something for the KissIt image thumbnailer.

**Comment by raiwa** [comment]
O.K. I have read more and saw now this:
"Avoid lazy-loading images that are in the first visible viewport #

You should avoid setting loading=lazy for any images that are in the first visible viewport.

It is recommended to only add loading=lazy to images which are positioned below the fold, if possible. Images that are eagerly loaded can be fetched right away, while images which are loaded lazily the browser currently needs to wait until it knows where the image is positioned on the page, which relies on the IntersectionObserver to be available."

Then you are right. It gets complicate and would need to be adressed with (java)scripts.

**Comment by ecartz** [comment]
Since there are no action items for core here, closing this issue to prepare for archiving this repository.
