### ISSUE TITLE
email PHP 7.4 Notice undefined index

### ISSUE THREAD

**Issue by robertkendrick** [gburton/CE-Phoenix#1048]
OSCOM CE Phoenix v1.0.7.15
PHP 7.4
[express.php Line 850](https://github.com/CE-PhoenixCart/PhoenixCart/blob/ebac86fdbdb27ce0553d02669702a7c7b834e9cf/ext/modules/payment/paypal/express.php#L850) there is an empty string (`$currency_code`) parameter passed to `formatCurrencyRaw()` in file OSCOM_PayPal.php.
This causes [Line 610](https://github.com/CE-PhoenixCart/PhoenixCart/blob/ebac86fdbdb27ce0553d02669702a7c7b834e9cf/includes/apps/paypal/OSCOM_PayPal.php#L610) in `formatCurrencyRaw()`   `if ( !isset($currency_code) ) { `   to return false  as it IS set to empty string.
So the   `if ( !isset($currency_code) ) {`     block not executed and $currency_code not set to a valid code and remains set as "".
This then results in Notice undefined index further into the code.

Suggest in express.php Line 850 the empty currency_code string is replaced with null.
$item_params['MAXAMT'] = $paypal_express->_app->formatCurrencyRaw($params['PAYMENTREQUEST_0_AMT'] + $expensive_rate + 100, **null**, 1);
This tests ok.

**Comment by ecartz** [comment]
I changed `formatCurrencyRaw` to call `currencies::format_raw`, which already handles this.  

https://github.com/CE-PhoenixCart/PhoenixCart/commit/03382b99fc3608353e0b4976ee883b8c8379ef70

In the long term, I would like to change express.php to call currencies directly rather than through the PayPal object.  But I don't want to track that on the old repository, so closing this.
