### ISSUE TITLE
configure.php files should be removed from the repo

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#765]
./admin/includes/configure.php and ./includes/configure.php  should not be included in the repo so people can just copy updates to their cart at will.  

Since you need to provide guidance on how to build these files, you could just give these files a different name, like configure-example.php.

**Comment by gburton** [comment]
Sorry, no they stay as is.

**Comment by scottcwilson** [comment]
OK, but then how can you run a store from a checked out copy of the repo?  You'll always have the configure files showing up as modified files, wouldn't you?

**Comment by yenoyen** [comment]
.gitignore file doesn't work?

**Comment by scottcwilson** [comment]
Oh ok - lots of projects check that file in, so it wouldn't work, but since this project doesn't, that's what I'll do.  Thanks!

**Comment by scottcwilson** [comment]
Hmmm... even with these files in .gitignore I get 

	modified:   admin/includes/configure.php
	modified:   includes/configure.php

when I do a git status.  How are other people handling this?

**Comment by scottcwilson** [comment]
Also, doing a `git stash --all` removes your configure.php files, thus rendering your store inoperable.

**Comment by BrockleyJohn** [comment]
I think you'll find that the vast majority of osc implementations have a lot more changes to core files than just those two!

Most other people are not putting their config files in the repo because they don't want to publish them and they're not paying a github subscription for private repos. Actually most of the people on the forums that use github at all are using it to find out what changed and then using editors or diff tools to get the changes into their site.

What I do for my client repos is keep the master branch an unchanged copy of Gary's repo master and a project branch that holds any files changed or added. I work on local clones and use sourcetree as a handy front end to all the git stuff. I add Gary's repo as a remote and pull his master changes straight in. The github clone of each repo is basically used as a backup of the local one. Distribution to the sites I do manually.

I have yet to try getting this to play with any of the cpanel git options on an ongoing basis, I suspect it's not straightforward if at all possible - I don't know if you can choose what branch to follow.

I do take your point that having differently named template files for the configures and the actual files not in the master but created by the installation instead of edited by it would take the No Core Changes approach to its logical conclusion.

**Comment by scottcwilson** [comment]
The use case is that I have a checked out copy of Phoenix where I am making changes with the intent to push to master.  I update it all the time, so it's in sync with master except for the configure files.  If I'm testing one thing but want to create a PR for something else, I can just do a git stash ... except then I lose my configure files. 

This problem would be solved by not having the configure files in master so people could check in local copies and have them in .gitignore. 

Also, private repos no longer require a subscription.
