### ISSUE TITLE
Stylesheet hooks unordered

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#802]
I've not had a problem with these until today but one site has decided to load the injectSiteStart hooks in an ideosyncratic order and styleSheets is coming out before bootStrap. Of course this prevents overriding boostrap styles in user.css

The obvious answer is another hook site eg. injectAfterSiteStart. PR?

**Comment by gburton** [comment]
Need to find out why that has happened.  Can you look into it, thanks.

**Comment by gburton** [comment]
These hooks (IIRC!) should be sorted by filename / class , so eg;

abc1
would display before
abc2
would display before
def

and so on.  Could you attempt to find why that's not happening?

If you can't get to the bottom of it, an idea may be to key sort the array perhaps in the call function in the hooks class file - could you try that also...  if that works, that would be good for core code in order to stop the same thing happening in the future.  TY.

**Comment by BrockleyJohn** [comment]
I will try and reproduce on a test site. It's possible that Steve's difficulties may have been the same underlying cause:
[https://forums.oscommerce.com/topic/493942-trouble-with-usercss-on-phoenix/](https://forums.oscommerce.com/topic/493942-trouble-with-usercss-on-phoenix/)

**Comment by BrockleyJohn** [comment]
Ok, so the hooks are read into a numeric array by the pseudo-oo dir mechanism. From the php manual
> Note: 
> The order in which directory entries are returned by the read method is system-dependent.

On one system I tried the order appears influenced by the last modified date, and came out:
`            [injectSiteStart] => Array
                (
                    [0] => fontAwesome
                    [1] => styleSheets
                    [2] => bootStrap
                )
`
Reading the files into an array and sorting it before loading the hooks solves the issue:
`Array
(
    [0] => bootStrap
    [1] => fontAwesome
    [2] => styleSheets
)`

**Comment by gburton** [comment]
TY for investigations.  Thrown me a PR ?

**Comment by gburton** [comment]
1.0.2.5
