### ISSUE TITLE
Pre-placed hooks - checkout_confirmation.php?

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#810]
Hi, in setting up a hook for 'must agree to terms' someone pointed out to me that checkout_confirmation.php did not have pre-placed hooks. I would think this page is a clear candidate for pre-placement of hooks being a key stage for customers to agree to terms before confirming their order.

Is it intended that this is addressed in a future version? Or is it intended that shop-owners do this themselves. Very easy to do but involves changing core code.

I'm sure you've thought of all of this, and got it in hand, so apologies if raising it here is nuisance-value only.

**Comment by gburton** [comment]
I believe most people thought that `agreement of terms` comes prior to starting the checkout (or as part of creating an account).  The conversation can likely be found somewhere at the forum.  

The idea of hooks is such that the addon maker makes their addon and then instead of telling people to "paste 20 lines of code" (as in the past) they instead tell people to paste 1 line of code (the hook).  Those "20 lines" are in the hook file.

Don't get hung up on hooks (see what I did there?).  They are only for allowing less copy/paste mistakes.  The fact there are some pre-placed hooks already...just makes that one line paste...already done.

**Comment by peterpil19** [comment]
Nice word play! In lots of jurisdictions, confirming terms before you order would be best pratice even if you have already agreed to terms when signing an account.

It just removes lots of room for argument about whether customer saw and agreed the terms because they might have set up an account 2 years ago and placed an order now (and for example, the terms have changed). Also checkout confirmation is when you actually see everything in one place so would make sense to get the customer to make the acknowledgement at that point. (This is the lawyer training in me now talking).

Your explanations make sense. I do think it would add value to have the pre-placed hooks in checkout_confirmation.php but will of course leave that up to you...! Thanks again.

**Comment by BrockleyJohn** [comment]
Your specific requirement does not need a hook and can be done with javascript in a header tag module with no edits.
Checkout confirmation button doesn't work unless the box is ticked to say they read the Ts & Cs.

**Comment by peterpil19** [comment]
No worries.  From forum, I had understood that pre-placements in core code in create_account.php and contact_us.php were to support captcha hooks (which also can be done by header tags). I just thought potentially inconsistent (when pointed out to me) that not also in checkout_confirmation.php also, that's all. Up to you guys, just thought I'd point it out.
