### ISSUE TITLE
Languages class

### ISSUE THREAD

**Issue by Piernas** [gburton/CE-Phoenix#828]
While updating an addon I found that the navbar languages module includes the  languages class. If you add another navbar module that uses this class and the stock module is loaded after it you get a fatal error even usin include_once.

I have two choices:
- Modifying the stock module and distributing with the addon.
- Hard coding a check if the stock module is installed and disabling it 'on the fly'

Both of them work; I'll use the second one but I suggest to modify the module to avoid this kind of  confilcts with addons by changing:

`include('includes/classes/language.php');`
to 
`include_once('includes/classes/language.php');`

in includes\modules\navbar_modules\templates\nb_languages.php

**Comment by ecartz** [comment]
At [includes\modules\navbar_modules\templates\nb_languages.php](https://github.com/gburton/CE-Phoenix/blob/a104616fefcfe6685cd81a003d7b57bc9534e738/includes/modules/navbar_modules/templates/tpl_nb_languages.php#L6)

It says 
`  if (!isset($lng) || (isset($lng) && !is_object($lng))) {`
`    include('includes/classes/language.php');`
`    $lng = new language;`
`  }`

So what are you doing that the next time `$lng` is not set and that code triggers?  If you set `$lng` properly when you loaded the language file, it would not include anything here.  

This seems more like a mistake in the App you're updating than something that needs changed here (although it should probably use `require` rather than `include` and it only needs to check `isset` once, but those won't affect functionality).

**Comment by gburton** [comment]
Please see @ecartz  comment above.

**Comment by Piernas** [comment]
I found what caused the issue. The addon was using its own language hanfling. It ignores the $lng variable in favor of a class property and loads languages class before other modules.
I'l change it to use it.
