### ISSUE TITLE
TableBlock

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#840]
This system outputs a table for headings and a table for content;

https://github.com/gburton/CE-Phoenix/blob/master/admin/includes/classes/table_block.php
extended by
https://github.com/gburton/CE-Phoenix/blob/master/admin/includes/classes/box.php
used at (eg)
https://github.com/gburton/CE-Phoenix/blob/master/admin/whos_online.php#L123-L124

I would like the system revamped so that when (eg) this is called;
https://github.com/gburton/CE-Phoenix/blob/master/admin/whos_online.php#L124

What gets output is a properly formed Table as so;

```
<table class="...">
  <thead class="...">
    <tr>
      <th>.......</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="...">.....</td>
    </tr>
    <tr>
      <td class="...">.....</td>
    </tr>
  </tbody>
</table>
```

Anyone up for the challenge of reworking the TableBlock file to do this?

**Comment by ecartz** [comment]
Wouldn't it be better to make it use a different template entirely?  This is exactly the kind of thing that has been deprecated and replaced with 

```
<div class="card">
  <span class="card-header">......</span>
  <div class="card-body">
    <div class="row">......</div>
    <div class="row">
      <div class="column">......</div>
      <div class="column">......</div>
     </div>
  </div>
</div>
```

Or similar.  I.e. I think that the problem is that it is using tableBlock at all.  I'm not really up on the Bootstrap classes.  I just copied this.  If you can get the classes right in the example here (five different types of element), I could implement them in infoBox.  

I mean the fundamental problem is that you don't need a table to describe the heading/contents structure.  The card structure makes more sense here.  Or perhaps the new Bootstrap has something better.

**Comment by gburton** [comment]
The bootstrapped admin changes are really only for prettification purposes.  So I want to keep it as close as possible (layout) as it is pre-bootstrap.

**Comment by ecartz** [comment]
Are we using layout to mean different things?  When I talk about layout in terms of the boxes, I mean that the box has a header and contents and the contents fit in a grid.  So the HTML that I suggested would have the same layout, only implemented differently.  

I'm not quite sure how you're using it.  I would say that you are using it to refer to the implementation, but you're talking about changing the implementation.  I actually think that your proposed structure is worse than the one that we have now.  Because your TH element will need a colspan to duplicate the current layout.  Which we'd have to calculate.  

But if we throw out the TH, we could have 

```
<div class="box">
  <span class="heading>.....</span>
  <div class="contents>
<!–– Some grid implementation; even tableBlock ––>
  </div>
</div>
```

That would be easier to code and I suspect it would be easier to style (prettify).  And semantically it would be correct.  Because the relation between heading and contents is not the same as the relation between THEAD and TBODY.  In particular, there would be no notion of the heading being in columns to match the contents.  

In some ways, your proposal changes the layout more than mine does.  Because THEAD and TBODY are the wrong paradigm here, even though they were the right paradigm in those center content tables.  A closer table-based equivalent to the current layout would be something like 

```
<table>
  <thead>
    <tr>
      <th>......</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
<!–– Some grid implementation; e.g. tableBlock ––>
      </td>
    </tr>
  </tbody>
</table>
```
But that's a lot more HTML for no actual advantage except that we're keeping the layout implementation table-based.  

You're replacing the 

```
    <table border="0" width="100%" cellspacing="0" cellpadding="2">
      <tr>
        <td><table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tr>
            <td class="pageHeading"><?php echo HEADING_TITLE; ?></td>
            <td class="pageHeading" align="right"><?php echo tep_draw_separator('pixel_trans.gif', HEADING_IMAGE_WIDTH, HEADING_IMAGE_HEIGHT); ?></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td>
```

nonsense with 

```
  <h1 class="display-4 mb-2"><?php echo HEADING_TITLE; ?></h1>

  <div class="table-responsive">
```

Why not do the same thing with the infoBoxes?  

It would be different if we were saving work by retaining some of the existing code.  But this would seem to be the long way around to reinvent a solution that won't work as well.

**Comment by gburton** [comment]
I would like to recreate the tables based layout at this point, using a properly formed table that has thead and tbody.

**Comment by gburton** [comment]
The other (potentially easier) option is to do away with the tableBlock class.  This would not hurt anything and may make things a lot more flexible.

The reason for not diverge the admin side too much is based on shopowners feedback - all they want is a prettification, so it is easy to move to Phoenix from older and still understand what is going on in the admin side (easy to find things, easy to do things, buttons in the same positions etc).

**Comment by gburton** [comment]
Here is the whos_online revamped using the a column and tables based layout;
[admin.zip](https://github.com/gburton/CE-Phoenix/files/3911054/admin.zip)
This is not using the tableBlock class, instead it just uses a hardcoded table and inserts the heading and content appropriately.  You can upload this to any recent Phoenix (1.0.3.0 onwards) and it should work well and look decent.  This is the extent of the bootstrapping in the admin side (per page) - it's prettification only.

**Comment by gburton** [comment]
The only "downside" to hardcoding the table in place (rather than utilize the tableBlock) is if a shopowner wanted to change from (eg) a table to (eg) a list-group.  

With tableBlock in use they would just change the one file.  Without it, they would have to hardcode change a few files.

But let's ask the question;

1.  how many shopowners would want to change the layout
2.  how many shopowners would know that tableBlock is what needs changing
3.  how many shopowners would be confident enough in php to make the changes

I'm pretty sure going down the hard-coded route is OK.  But I'm open to persuasion on it.

**Comment by ecartz** [comment]
I can find no examples of boxes with multiple lines of headings, so you could rip that out and just put in a straight echo.  

Wouldn't it be easier to put the layout you created in the template that I already coded rather than reinvent it on every page?  You could be done with this if you did.  Because my change is purely in the infoBox and one new file.  So if you replace my layout with yours and hardcode the contents inside the infoBox method, you will have gotten rid of tableBlock (just remove the extends).  And still have done it for every box today without touching any more files (except maybe whos_online to make it like the others).  

As best I can see, that's about the same work as hard coding one more page (rather than twenty).  And when shop owners want the next prettification, we can still just change all the infoboxes in one place.

**Comment by ecartz** [comment]
Another way of saying the same thing.  

Putting the layout code (whichever layout code) in the template is easier to change both now and in the future.  For us, shop owners, and anyone else.  It's the least code way as well, as hardcoding just means writing the same code that would appear once in the template twenty times in the pages.  

And this still lets us get rid of tableBlock and the menuBox code.  While retaining a common format that everyone will probably use.  If you hardcode the infobox, then some people are going to release Apps with their own layouts.  Because of course there is no penalty to doing so.  There's just as much work to implement the common layout as anything else.  They can actually save a bit of work by hardcoding directly into a table rather than copying the layout from another page.  

Hardcoding is more work now and in the future.  And I don't see that we gain anything from it, since you're waiting until after the header/contents stuff is built to hardcode it.

**Comment by gburton** [comment]
I'll give it a go with your tpl - thanks @ecartz

**Comment by gburton** [comment]
With some jiggery-pokery this seems to work - thanks @ecartz - I'll do some more intense testing on it...to see if I can break it.

**Comment by ecartz** [comment]
I found that [messageStack](https://github.com/gburton/CE-Phoenix/blob/master/admin/includes/classes/message_stack.php) also extends tableBlock.  I would think that it could easily display as something else (e.g. a `<ul>`) but it doesn't at the moment.  Sample code:  

```
public function output() {
  $html = '';
  if (!empty($this->errors)) {
    $html = "<ul>\n";
    foreach ($this->errors as $message) {
      $html .= '  <li';
      if (!empty($message['params']) {
        $html .= $message['params'];
      }
      $html .= '>' . $message['text'] . "</li>\n";
    }
    $html .= "</ul>\n";
  }

  return $html;
}
```

I mention this only so that we don't delete tableBlock before changing messageStack.  I'm fine with leaving it if you're not ready to make a replacement work.  I haven't tried this code.  It's just a possibility.
