### ISSUE TITLE
use of wildcard in queries

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#848]
It would be useful to change as much queries to wildcard as it has been done in admin/categories.php for the product query in line 395.
Doing the same in line 709, 874, 876 etc. would allow to use third party data (columns added for addons) in hooks without the need to repeat queries.
The same in other files like admin/orders.php, customers.php etc. as well as in shop side.

**Comment by gburton** [comment]
Sure, go ahead and push to 1041

**Comment by ecartz** [comment]
Be careful about conflicts though.  Weird things happen if you get the same column from multiple tables with different values.  This works best when any common columns are JOINed.

**Comment by raiwa** [comment]
Thanks for the advice. I made already admin customers and orders. Once you finished we'll compare and merge the changes if needed.

**Comment by raiwa** [comment]
@ecartz > Be careful about conflicts though. Weird things happen if you get the same column from multiple tables with different values. 
Can you point me to a concrete example where this occurs. I couldn't see any preoblematic query in this sense.

**Comment by ecartz** [comment]
> Can you point me to a concrete example where this occurs. I couldn't see any problematic query in this sense.

Well, since we hadn't been doing this in this code base, I don't know of one here.  

An example of a situation where it could happen would be if there was a query looking for reviews on a product in an order.  Where both the order and the review have a customers_id field but the order and review are associated with different customers.  I'm not sure anyone is doing anything like this though.  

Another example would be if you're doing a self join.  For example if you wanted to display information about a category and its parent category.  But again, I don't know that any of the framework queries have that.  Although I'm sure I've had to do things like that.  

This isn't:  there are potholes all over the codebase.  It's a maybe you should, when making the change, scan for possibilities.  You're looking at the queries when you make the change.  So you can see if there's anything problematic about them.

**Comment by raiwa** [comment]
I checked all queries I modified and didn't see any possible problem.
I also had a look into the tables where possible problems may occur and for example between customer and address book and orders table, which could be a source of duplicated column names with different content, it has been taken care to use different column names.
I also wonder if it wouldn't be necessary, even retrieving the columns individually, to take care for it. However, I finished the modifications and will pull the forks. Please check and solve possible conflicts with you modifications in customer.php and orders.php by manual editing.
rgds
Rainer

**Comment by raiwa** [comment]
Updated to 1.0.4.1 and pushed to 1.0.4.1.
I checked and tested all modified pages. Seems to be all good.

**Comment by gburton** [comment]
1041
