### ISSUE TITLE
add preplaced hook for order mail manipulation

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#865]
In admin/orders.php line 54 add:
`            $OSCOM_Hooks->call('orders', 'orderMail');`

and
checkout_process.php line 278 add:
`  $OSCOM_Hooks->call('checkout_process', 'orderMail');`

Both just before the tep_mail line, would allow to easy manipulate the mails.

**Comment by ecartz** [comment]
I'm doing things a different way.  In part because I don't want to have a hard dependence on email as a notification method.  

Can you explain more about what you are trying to do?  Are you adding information?  Removing?  Changing?  What kind of information?

**Comment by raiwa** [comment]
For example in the PWA app (Purchase without account/guest checkout) I add specific text for guests and a link to reviews write with a pwa id. So guest customers can write a review for their products.
Similar in the new reviews/testimonials manager app.
In the points and rewards addon additional info about redeemed/earned points is added to the mails.
In all of this examples something is added to the $mail variable via hook or in older versions by core change.

**Comment by ecartz** [comment]
I was thinking about proposing part of the changes separately, so I made a branch for it at https://github.com/ecartz/CE-Phoenix/tree/break-up-checkout-process

That's not finished/tested code.  It's part of what I'm doing that I broke out separately when you were talking about making checkout changes.  

Under the current method, I could easily add a hook before the mail function call so that you could append stuff.  But the next iteration might break it, as the next step is to generalize away from email.  Of course, a lot of other information would get dropped by, for example, a text message.  So perhaps it would link to an account_history_info page instead of trying to include the entire email.  So PWA would want to add text to that page rather than the text message.  And of course you'd want to add your special sauce to bypass login for that link.  So that may not be as much of an issue as I first thought.  It will still break, but no more than it would have in any case.  

For a review/testimonial link, wouldn't it be better to add prior to the creation of `$products_ordered` so that it appears with the rest of the product information?  As I understand it, you're talking about always appending your custom information.  So there's the regular email and then some additional text at the bottom.  But it sounds like some information should be within the existing email.

**Comment by raiwa** [comment]
For guest/pwa orders, no account exists where a customer could access to information. The only link/info for his order is the order confirmation mail and the admin order status update mail.
So order confirmation mails should be modificable by Apps. In which way, depends on how it is done in core.

**Comment by ecartz** [comment]
Right.  But if we add a way to use a text message notification instead of an email, then the message is unlikely to have enough capacity to support any of the things that you want to do, much less all of them combined with the existing message.  It could basically say, you've placed an order, go to the link for more information.  So, much like you enable the link for review writing (which would normally require login), you will have to enable an account history info link for PWA.  Even if there's no account for there to be history.  

But that's not the real point here.  I'm fine with adding a hook (or two or three) into the order email.  I'm just saying that you should expect that to only work intermittently as soon as someone enables a notification method other than giant email.  The only change I would make is that on the catalog side, use a siteWide hook with parameters:  

```
$OSCOM_Hooks->call('siteWide', 'orderMail', ['order' => $order, 'email' => &$email_order]);
```

Because not all order emails are sent by checkout_process and I think we're better off not faking it in the places that aren't.  

Another alternative would be 

```
$email_order .= $OSCOM_Hooks->call('siteWide', 'appendToOrderMail', ['order' => $order]);
```

That would seem to cover your needs.  A little less powerful but requires less responsibility.  I don't have a strong opinion about which is better.

**Comment by ecartz** [comment]
@raiwa If it's not obvious, I'm waiting for feedback on whether one or both of the alternatives that I suggested is acceptable to you before making a change.

**Comment by raiwa** [comment]
Hello Matt,
I'm sorry, it was not obvious for me. Please add any of your suggestions which you consider preferable. I'm fine for now if it allows to add info for specific apps to the mail content.
Once the checkout process has been updated, I believe I'll find a way to do it as it will be supported and done in core.
Best regards and a happy New Year
Rainer

**Comment by ecartz** [comment]
This is currently implemented at https://github.com/gburton/CE-Phoenix/blob/44556a201fc8fdde7d261210402c55519d362af0/includes/functions/general.php#L857 and should go live with 1.0.5.1

**Comment by raiwa** [comment]
Thank you, I'll have a look and try when I find some time :-)

**Comment by ecartz** [comment]
1.0.5.1 is live.

**Comment by ecartz** [comment]
@raiwa I would like to change how this works and was wondering where you were in using it.  I'm looking for answers like 

1.  Haven't started.
2.  In the middle of testing.
3.  "Completed testing and hoping you're not making additional changes that would cause me to retest."
