### ISSUE TITLE
Addition [core code] - Product Sort Order

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#892]
I've had a number of requests for addition of "product sort order" so that shopowners can more easily have certain products at the top of (eg) a category page.  Where a product list is from a number of categories (eg, products_new.php, "new products for <month> on index page", specials.php), I propose to leave the sorting as is.

Some of this can be done with Hooks, but some of the below needs dumping onto core.

**admin / categories.php - when looking at product list**
- Have a new column (next to the red/green status column) that shows the sort order (if given). 
- Order the output of the list by the sort_order, products_name
- Maybe have some type of interface to allow shopowners to update sort_order(s) directly in this list 

**admin / categories.php - when adding/editing a product**
- have a sort order input field [this could easily be hooked, but doesn't really make sense to do so]

**Shop Side, when looking at a category**
- Order the list (as default) by sort_order, products_name

Does anyone see any downsides with any of the above?
I'm not asking for anyone to actually do the coding, just for general comments etc.

Of course there are better options available such as a Content Module to highlight certain products - but as we have a category sort_order feature there is no reason NOT to have a products sort_order also.  Except as already pointed out, when there is a list of products in mixed categories.

What have I not thought about ?

**Comment by MOPS-DanCole** [comment]
That makes perfect sense to me and would be an awesome addition.

**Comment by azpro-git** [comment]
The addition of a product sort_order is sure very helpful.  We use this and therefore added **column** products_sort_order to the **table** products_to_categories to overcome the possible conflicts with products being placed in different categories.

I hope this helps!

**Comment by BrockleyJohn** [comment]
Product sort order doesn't work on the edit product page of admin/categories.php as it's within category and the product can be in multiple categories. 

It is most usable with an interface that's not currently present in core. In my modular categories addon it's maintained in a form on the panel on the right of the list view in one module and I have a prototype module that does it by drag and drop. Both these approaches are quite a long way from the current code needing lots more context than just the attribute update.

The standard addon has a separate page to maintain sort orders within each category so you can renumber the whole lot at once.

It's definitely a good thing to have some support for it though, nearly all shopowners seem to want it sooner or later.

**Comment by ecartz** [comment]
One argument against doing this is that it is hard to index properly.  What you really want is a sort_order, products_name index, but those would be on different tables.  

I would kind of rather make the core modifications to be able to change the sort order and make the actual sort order changes outside core (possibly in a module or database-defined hook that ships with core).  Then people who only put products in a single category in a single language can make it work one way (sort order on products).  And people who only have products in a single language but multiple categories per product can make it work a different way (sort order on products_to_categories).  And people who only have one category per product can make it work a different way (sort order on products_description).  And people who have both multiple category products and multiple languages can implement it in yet another way (a products_to_categories_description table?).  

So 

> * Have a new column (next to the red/green status column) that shows the sort order (if given).

becomes 

* Allow hooks to add columns to the categories/products catalog table (and possibly other HTML tables).  

This might require moving from hard coded tables to some sort of table object.  So specify the columns (with headers) and the data to display mapping for each column.  

> * Order the output of the list by the sort_order, products_name

* Allow hooks to set the sort order, possibly shipping the default order as a database-defined hook (so it can be overridden).  

> * Maybe have some type of interface to allow shopowners to update sort_order(s) directly in this list

Presumably you could do this with your new column.  Might also require a change to allow hooks to add a form to a table.  

> * have a sort order input field [this could easily be hooked, but doesn't really make sense to do so]

I think it makes sense to do this by a database-defined hook so it can be overridden without requiring the store owner to modify or delete a core file.  Or do silly things like assemble the database query twice (once the default way and then a second time in the way that actually runs, where the second way needs to do almost everything the same).  

> * Order the list (as default) by sort_order, products_name

Again, I think that this should be done by adding the ability to set the sort order by hook and then possibly setting the sort order with a database-defined hook that can be overridden.  

This is exactly the kind of use case for which I wanted database-defined hooks.  Behavior that we want core to provide a sane default but which it is reasonable for App developers to override.  

A side benefit of this is that we could make the initial core default exactly match the current core behavior and then release your version as Supporters' code.  Because it is entirely reasonable for Supporters' code to have arbitrary requirements like single-language stores or only one category per product.  But I don't think that we should add that kind of restriction to core.  Nor should we make the ultra-complicated handling of multiple-category, multiple-language product sort order core.  Because most people won't need it and those who do will want it configured in different ways.

**Comment by gburton** [comment]
If we put the sort_order on the products_to_categories (p2c) table...I'm not sure what good that would do?  Linked products don't show here (or do they)?  And duplicate products have their own entry anyway...in the products table...

Am I missing something ?

**Comment by gburton** [comment]
> Am I missing something ?

To answer myself - yes I am.  Both a linked product and a duplicated product show up in the p2c table.  So it would be a good idea to have the sort order column in the p2c table...

**Comment by BrockleyJohn** [comment]
> One argument against doing this is that it is hard to index properly. What you really want is a sort_order, products_name index, but those would be on different tables.

The index is on the products_to_categories table!

**Comment by dominiosc** [comment]
Is great feature what I hope is implemented.
Let me suggest an additional related function, the otherwise, you can set products how discontinued, so not show by default in list or search results unless filter this to show.
You only can access if know direct link, that is user have saved link, page linked, indexed or bot search, with this option you not need to disable products.

**Comment by OmarMasheh** [comment]
is there any news about product sort order?

**Comment by gburton** [comment]
> is there any news about product sort order?

https://forums.oscommerce.com/topic/495586-code-hacks-to-add-product-sort-order-to-categories/?do=findComment&comment=1810505

6 posts from there, no one has yet tested and reported back

**Comment by OmarMasheh** [comment]
I just try it on 1.0.7.04 and its not working

**Comment by gburton** [comment]
> I just try it on 1.0.7.04 and its not working

You could maybe expand on "its not working" in the Thread I linked to at the forum?

Eg;  
what did you try?
what did you not?
what was the error message?
what does not look cosmetically correct?
and so on.

**Comment by gburton** [comment]
For now closed, until feedback is given by loads more people and/or workable code is made by someone.

**Comment by OmarMasheh** [comment]
really sorry that I didn't give any details
here is the errors 
1- ` PHP Notice:  Undefined index: sort in /includes/system/segments/sortable_product_columns.php on line 47`
and the line is 
`$sort_order = substr($_GET['sort'], -1);`  
2- `PHP Notice:  Undefined index: sort in /includes/system/segments/sortable_product_columns.php  on line 49 Notice : Undefined offset: -1 in` 
and the line is
` switch ($column_list[$sort_col-1]) {`
same line also has error 
`PHP Notice:  Undefined offset: -1 in PHP Notice:  Undefined index: sort in    /includes/system/segments/sortable_product_columns.php on line 49 `

3- `PHP Notice:  Undefined index: sort in /includes/modules/content/index_products/cm_ip_product_listing.php on line 120` 
and the line 
` $output .= tep_draw_hidden_field('sort', $_GET['sort']);`

4- `PHP Notice:  Undefined index: sort in /templates/default/includes/components/product_listing.php on line 84
`
and the line is 
` $lc_text = tep_create_sort_heading($_GET['sort'], $i+1, $lc_text);`

**Comment by OmarMasheh** [comment]
Sorry burt , 
after I try it again it's working as it should .. I think the problem was copying  from the oscommerce forum and paste it on the files ... there was some extra marks when I pasted  .. I had same kind of issue before by copying from the oscommerce forum.
I'm using Product Sort Within Category BS by @BrockleyJohn for admin side .. after editing the sql query ( there is some error but its working )
