### ISSUE TITLE
Proposal - multi language install

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#948]
By doing the  installation stuff from scratch I wondered whether it would be possible to have the installation process multi - linguar? I would offer to help with the translation for a language ...

**Comment by ecartz** [comment]
To be truly multilingual, we'd also have to change the database values in the configuration table.  E.g. all those True/False selections.  The headings and descriptions are also all English.  Until we do that, it won't be multilingual for the store owner.  Currently at least some ability to read English is required to administer the store and that will continue unless we fix the configuration problem.  

The configuration problem is not just the translations themselves.  It is also accessing them and storing them (because we want to store them in a language independent fashion so changing languages doesn't break the store).  

I'm somewhat against fixing just the install (which would probably be easy), as it would raise false hopes.  As is, someone can see at install time that English is required.  So I would rather fix the install last rather than first.

**Comment by gburton** [comment]
I do not want to go down the path of shipping Phoenix with translations already included.   That just adds more stuff to maintain when we don't have enough support (from other people) to maintain what is already there.

I hear what you're saying, but it's not where we should be looking as a "to do".

**Comment by ecartz** [comment]
I think the problem here is less about shipping with more translations and more about the install having the capacity to be translated.  As is, the text is hard coded.  So even if someone were willing to download translations for it (separately from core), they can't.  I.e. there is a technical problem to be solved before we get to the point of translating.  

I suppose that someone could replace the install files with translated versions.  That would require no core intervention and would simply be a matter of the translators maintaining their own install folders.  

I would advise against starting that at the moment, as there are some changes that I'd like to make to the install process in the not too distant future.  And that approach is more update intensive.
