### ISSUE TITLE
Split Category and Manufacturers in Index

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#953]
I propose this change which allows for some simplification of the index.php page;  https://github.com/gburton/CE-Phoenix/commits/simplify_index

1.  changes $category_depth FROM "top" to "index"
2.  add in a new $category_depth for "index_manufacturers"

We can now use easier logic to determine what should show.  I have made manufacturer modules for index_manufacturers which should be installed in the usual way (in admin).

This is tested and working in latest v1.0.5.7.  

If this is deemed suitable/useful - the index_products modules can be amended to remove all trace of "manufacturer/brand" and be renamed from index_products to (eg) index_category

After the recode and rename of index_products we then have the index.php split out into 4 distinct groups;

- index [hello page]
- index_nested [a category that has subcategories]
- index_category [a category that has products]
- index_manufacturer [a manufacturer page]

I am open to ideas.

**Comment by ecartz** [comment]
I would rather change top and index to index_top or similar (could also be any of index_hello, index_welcome, index_greeting, etc.).  

Also consider what would happen if we renamed $category_depth to $specified or similar.  Then the values might be 

* none
* nested
* leaf
* manufacturer

And we could call oscTemplate like 

```
$oscTemplate->getContent("index_$specified");
```

We also might want to think more about how we want to behave when both a category and a manufacturer are specified.  Or when there are both products and subcategories in a category.  Yes, the traditional behavior has been to only allow one or the other.  Do we still want to do it that way?  

I ask because I think it is quite possible that store owners might want to differentiate differently.  For example, they may want the same boxes to show on all pages where a category is specified.  Or they may want to differentiate between categories with subcategories and products and categories with just subcategories or just products.  Worse, they may want to mix those two situations.  For some elements, they may want to show on all pages where a category is specified.  For others, they may want to show only where the category has subcategories or products.  Perhaps they want to choose to show a manufacturer page whenever a manufacturer is specified rather than only when a category isn't.  

This hardens those choices where we may want to make them more flexible instead.  

More generally, as long as we're there, I'd like to remove the redundant `isset` before `!empty`.  The `empty($var)` construct is exactly equivalent to `!isset($var) || !$var`.  So we can just say 

```
  } elseif (!empty($_GET['manufacturers_id'])) {
```

Or even something like 

```
  } elseif (isset($brand) && ($brand instanceof manufacturer)) {
```
or 
```
  } elseif (($brand ?? null) instanceof manufacturer) {
```

**Comment by gburton** [comment]
Changing "top" to "index" is simplistic as we already have a "index" group of modules.  I'd prefer to keep changes relatively simple for a period of time, at least until this Virus is 'done' and people can more easily help with testing.  The change I propose is very straightforward and causes no unforeseen gremlins...

**Comment by ecartz** [comment]
By that argument, we should leave index_category as index_products.  

Is it really harder to test now?  Most of the virus related restrictions are about interacting with strangers.  Less time interacting with strangers should leave more time for testing not less.

**Comment by gburton** [comment]
> By that argument, we should leave index_category as index_products.

Manufacturers also show products.  
It makes sense (at least, to me) to have no "*_products"... which means;

manufacturer => products
category => products

> Is it really harder to test now? 

Yes.  Sales of online things are up, so shopowners are concentrating on online sales more.  Especially true of those who also run retail.

**Comment by azpro-git** [comment]
>  
>     index [hello page]
>     index_nested [a category that has subcategories]
>     index_category [a category that has products]
>     index_manufacturer [a manufacturer page]
> 
This is exactly what we have done (and that is before Phoenix) ... It really has a lot of advantages/possibilities.

EG you can code a different left category box which only shows the categories for a specific manufacturer. That way we created kind of "brandshops" ... For me (coding alone) it had some pitfalls - but all in all it makes the code easier.

But it is not an easy job ... think of SEO and breadcrumbs - they all need to make sense. Futhermore we needed to modularize sorting / filtering / paging in order to avoid double code.

I am sure you guys all understand that and come up with good solutions.

**Comment by gburton** [comment]
> This is exactly what we have done (and that is before Phoenix)

Do you have yours as 4 separate standalone pages @azpro-git or just 1 page with 4 seperate module areas ?   Thanks

**Comment by ecartz** [comment]
> It makes sense (at least, to me) to have no "*_products"... which means;

And it makes sense to me to go ahead and make the welcome page follow the same paradigm as everything else.  So instead of having an index and index_things, we have just index_things.  We could eventually allow people to add to all index groups with index (we don't need to make that change now).  

My point is that if we are renaming one group (index_products to index_category or whatever), then we might as well rename two groups (index and index_products).  Or if we think that renaming risks gremlins, we could rename no groups and just add one.  Pushing off renames until later.  

Note that in your new scheme, you would have two category groups (nested and category), one of which is called category.  I'm not sure that it is worse to have two product groups (products and manufacturer) one of which is called products.  We could of course fix the ambiguous name problem by naming it leaf or similar.  But if we leave it as products, we minimize current changes and we can decide a final name at leisure.  Or move to a different paradigm entirely later.  E.g. one that also unites the search and specials pages.  But we can work out which of that we want to do later.  

Just adding an index_manufacturer content group is enough to allow the thing that you currently want to do.  We don't have to rename anything.  But if we start renaming, I'd prefer to work out a complete scheme now.  So we don't later decide that index_category is wrong and we really need it to be index_bottom or index_leaf or index_end or ....

**Comment by BrockleyJohn** [comment]
Is support for category filtered by manufacturer and manufacturer filtered by category being removed? I'm not clear that the differentiation between product list pages is anything other than arbitrary. I've written brand promotion modules that appear whenever that manufacturer is selected, category promotion that shows whenever that category or a sub of it is selected and so on. 

I've also done a module for someone to show subcategories on a product list page which was not supported on osc classic.

I'd go the other way - only differentiate between top and category - maybe even separate pages.

Not that I've looked at your code, it may avoid this issue: too many subtypes of page leads to too many content modules doing the same thing in different folders.

**Comment by gburton** [comment]
> Or if we think that renaming risks gremlins, we could rename no groups and just add one. Pushing off renames until later

This.

**Comment by azpro-git** [comment]
> Do you have yours as 4 separate standalone pages @azpro-git or just 1 page with 4 seperate module areas ? Thanks

Gary - I am not entirely sure I understand what you ask. But yes - we stil use only (1) index.php and have put all the php/mysql logic in modules ... 

But reading @BrockleyJohn  's post (too many content modules doing the same thing in different folders) is something I recognize and should be taken in consideration. After I finished the Modules I asked myself why I did not use a class method of coding - which might reduce double modules (at least for the mysql output). 

Do bare in mind I would still qualify myself as **not a professional coder** - so my observations are allways based on coding experience (trial and error for that matter) and I do lack Architecture skills.

**Comment by ecartz** [comment]
> Not that I've looked at your code, it may avoid this issue: too many subtypes of page leads to too many content modules doing the same thing in different folders.

I did look at the code and it does have this issue.  But he's saying that he doesn't want to engage in the larger task of addressing it now, as fixing that is a more profound architectural change that may have unknown side effects (a.k.a. gremlins).  

While you are correct that this makes that particular problem one worse, it doesn't create the problem (which already exists).  It does simplify the logic in some places (because currently we have to check for both category depth and the existence of a manufacturers_id) while increasing code duplication (because some places don't care about that distinction).  

And this change would allow store owners to create brand specific messaging.  Which presumably matters to at least one store owner; otherwise, he wouldn't be talking about it.

**Comment by gburton** [comment]
As a side note, I'd also like to explore routing things into index.php.  For example the "info pages" (condtions etc) as well as cookie_usage and probably others that don't really need their own page.

Down the line obviously.

**Comment by ecartz** [comment]
> As a side note, I'd also like to explore routing things into index.php. For example the "info pages" (condtions etc) as well as cookie_usage and probably others that don't really need their own page.

The problem with that is that it makes it harder for the code to be cross platform with reasonable URLs.  

I mean, osC3 and Zen Cart handled it by doing index.php?page=real_name which avoids having twenty files that say 

include application_top
include language file
include template
include application_bottom

but does so at the expense of making the URL ugly.  

We can make the URL not ugly with mod_rewrite.  But then we have to maintain mod_rewrite for every situation *and* we are limited to Apache.  

I mean, we could eliminate every other page with an index.php that said 

include application_top
$page = determine_page();
include "$language/$page.php";
if (file_exists("$code/$page.php") {
  include "$code/$page.php";
}
include "$template/$page.php";
include application_bottom

but should we?  It just pushes the problem into determining the page.  So every page goes from real_name.php to index.php?page=real_name and we need mod_rewrite to get back to more sane URLs like /real_name/ or real_name.html

And of course we can still have those names if we use mod_rewrite with the current method.  If we are willing to make Apache with mod_rewrite a hard requirement, we could make the names look like anything so long as there is a unique mapping.  That's why amazon.com has those /seo-keywords-here/handler/identifier URLs.  Which it handles by /ignoring-everything-here/handler/identifier and just using the handler/identifier to specify where the page should go.

**Comment by azpro-git** [comment]
> I mean, osC3 and Zen Cart handled it by doing index.php?page=real_name

> but does so at the expense of making the URL ugly.

I would say - don't go there .... makes it pretty complicated in the end. I understand you could/would get rid of a few files shortening the codebase to maintain - but those files (conditions.php etc) are the easy ones. 

I would focus on (simplifying) index.php by modularizing and hence give shopowners / app developers more control. The latter may allready bring extra needs for hooks etc.

Just my 2 cents ..

**Comment by ecartz** [comment]
We could reduce the number of things that we break by separating the concepts of group to call and category_depth.  So category depth would keep its current values and then we would map those to groups.  

```
function tep_index_map_category_depth_to_content_group($category_depth) {
  switch ($category_depth) {
    case 'top':
      return 'index';
    case 'products':
      return 'index_products';
    case 'nested':
      return 'index_nested';
    default:
      return $category_depth;
  }
}
```
later 
```
$oscTemplate->getContent(tep_index_map_category_depth_to_content_group($category_depth));
```

Then everything that relies on the current setting of $category_depth will still work and we'll still have a simpler index page.  Not quite as much simpler as originally suggested, but we can fix that as part of some larger project.

**Comment by gburton** [comment]
This is what uses category_depth;

https://github.com/gburton/CE-Phoenix/search?q=category_depth&unscoped_q=category_depth

We would be changing top to index, simply to allow a simplification of index.php

**Comment by ecartz** [comment]
> This is what uses category_depth

In core!

We don't know what uses category_depth outside core.  If you are concerned with sudden breaks of production stores that try to update, this is exactly the kind of change that would have unpredictable effects.  Because production stores use Apps and custom code that we can't predict.  

We can certainly change everything in core.  But that won't keep Apps and custom code used in live stores from breaking.  

I'm fine with pursuing the larger set of changes.  But if we're doing that, I think that we should rename the index content group.  Yes, that will break any modules that are using the old version.  But again, we can fix all those in core and leave App developers to fix those in Apps.  

If we are creating a rule to avoid breaking changes, then we should avoid breaking changes.  Which means not changing category_depth at all.  Perhaps we can get away with adding manufacturer as a category depth.  But we shouldn't rename any of the existing depths.

**Comment by gburton** [comment]
If we worried about every addon, we would stil be at osc v2.2
Let's get real.  Closed.  I'll revisit this at some point.
