### ISSUE TITLE
closing php tag

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#962]
As asked already before: I thought it is good practise to ommit the closing ?> ... but with the new version I notice that there are still many in there although many files were changed ... is the goal to keep the things as they are or to change them when a file is changed by whatever reason.

Just for consistency

**Comment by ecartz** [comment]
Specific file or files as examples?  

Note that the general rule is that if a file produces output itself, e.g. almost any of the root catalog or admin files, that it should close any PHP tags.  It's when the file is a pure code file that it's recommended to omit it.  For example, language files are pure code files.  So the closing tag should be omitted.  But of course there are many language files that haven't been changed in ages.  We aren't editing them just to edit them.

**Comment by cupidare** [comment]
I am referring to the output files. It is a little bit confusing following the argumentation and I didn't find a good source with an explanation, which is right and which wrong. Some finde it useful to always omit it some say that mixed files shall conatin a closing tag... but all I found was argumentation and no strictly well defined rule. Therefore it would be nice to have such a definition here at oscommerce. I believe this discussion is more or less "cosmetic" but I just wanted to seek a general "guide"

**Comment by gburton** [comment]
It as exactly as Matt says.
We omit closing php tag, but we do not change files for the sake of that.  If files get changed for some other reason (eg a language change), the end php tag can be removed if appropriate, if the person making the changes remembers to do so.  

It is unimportant, this is a detail that is not even worth spending 60 seconds thinking about.

**Comment by ecartz** [comment]
I'm willing to promulgate a rule if that helps.  

If a file includes a closing ?> tag because it emits HTML after that closing tag, it should close all tags.  Or if it emits HTML before any <?php tag, it should close all tags.  Examples of these are template files.  

If a file never emits any HTML, it should not close the ?> at the end of the file but should only have the <?php at the beginning.  Examples of files like this are languages files and those with class or function definitions.
