### ISSUE TITLE
Move date format management to admin

### ISSUE THREAD

**Issue by LeeFoster** [gburton/CE-Phoenix#977]
Suggest moving date format management to avoid having to repeatedly change the core English language file should it be overwritten by an update.

**Comment by ecartz** [comment]
Better would be to change things so that the customized language files aren't overwritten by updates.  Date format is set in the language files because it is language/locale specific.  If this is a problem for date format, then it is equally a problem for other custom per language changes, like wording.  And of course, if we moved it out of the language files, then translators couldn't put the correct date format in the language file.  Which would make things harder for many store owners.  

This is probably the kind of change that would be better discussed in the Phoenix Club.  Because the relatively small number of people who read GitHub issues aren't necessarily the ones who would be most impacted.
